In [1]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Pavan","25","Vijayawada"])
    writer.writerow(["mani","23","Hyderabad"])

In [2]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Pavan', '25', 'Vijayawada']
['mani', '23', 'Hyderabad']


In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
l=range(1000)
%timeit [i**2 for i in l]

164 μs ± 7.55 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## creating arrays

In [7]:
a=np.array([1,2,3,4]) #one dimensional array or vectors

In [8]:
print(a.ndim)

1


In [9]:
b=np.array([[1,2,3],[4,5,5]]) #two dimensional array or matrix
print(b)

[[1 2 3]
 [4 5 5]]


In [10]:
print(b.ndim)

2


In [11]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #3 dimensional (in cube)
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3


In [12]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


## functions for creating array

In [13]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


## using linspace

In [15]:

a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [16]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [20]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
print(np.diag(a))

[1 2 3 4]


## Basic data types

In [22]:
a=np.arange(10)
print(a.dtype)

int64


In [23]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [24]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## other data types

In [25]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [26]:
a=np.array([True,False])
print(a.dtype)

bool


In [27]:
a=np.array(["aditya degree college"])
print(a.dtype) #unicode string type

<U21


## Indexing and slicing

In [28]:
a=np.arange(10)
print(a[5])

5


In [29]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
print(a[0,0])

1


In [31]:
b=np.arange(1,10)
print(b[2:5])

[3 4 5]


##  slicing

In [32]:
import numpy as np
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(a[1:8:3])

[1 4 7]


In [34]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [35]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [36]:
a[1,1]=5
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 3]]


In [37]:
a=np.arange(10)
a[4:]=9
a

array([0, 1, 2, 3, 9, 9, 9, 9, 9, 9])

## copying and viewing

In [39]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [40]:
print(np.shares_memory(a,b))

True


In [41]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [42]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [43]:
print(np.shares_memory(a,b))

False


In [44]:
print(b.base)

None


## random number generator

In [47]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)

[19  7  9 18  9 10 12  6 13 15 17  1 12 19  4]


In [48]:
mask=(a%2==0)
new_a=a[mask]
print(new_a)

[18 10 12  6 12  4]


In [49]:
a[mask]=-1
print(a)

[19  7  9 -1  9 -1 -1 -1 13 15 17  1 -1 19 -1]


## Element wise operation

## 1. Basic operation

In [51]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [52]:
print(a**2)

[ 1  4  9 16]


## All arithmetic operates element wise

In [53]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [54]:
print(a*b)

[2. 4. 6. 8.]


In [55]:
c=np.diag([1,2,3,4])
print(c)
print(c *c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [56]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## Comparision operator

In [57]:
a=np.array([1,2,6])
b=np.array([4,5,6])
print(a==b)

[False False  True]


In [58]:
print(a<b)

[ True  True False]


In [59]:
print(a>b)

[False False False]


In [60]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))

True


## logical operator

In [61]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [62]:
print(np.logical_and(a,b))

[ True False False False]


In [63]:
print(np.logical_not(a))

[False  True False  True]


## trignomerty/ transcendental functions